# Все тексты бота на 3 языках
TEXTS = {
    "ru": {
        "welcome": (
            "🌿 *Добро пожаловать в Bazilik!*\n\n"
            "🍱 Мы доставляем свежие домашние обеды\n"
            "прямо в ваш офис каждый день\n\n"
            "✅ Выбирайте из 3 блюд ежедневно\n"
            "✅ Заказывайте до 20:00\n"
            "✅ Получайте обед с 12:00 до 13:00\n"
            "✅ Копите баллы и получайте бонусы\n\n"
            "📝 Для начала введите ваше *полное имя*:"
        ),
        "select_lang": "🌐 Выберите язык:",
        "enter_name": "👋 Введите ваше *полное имя* (Имя Фамилия):",
        "enter_phone": "📱 Поделитесь вашим номером телефона:\nНажмите кнопку ниже 👇",
        "enter_company": "🏢 Введите название вашей *компании/организации*:",
        "enter_address": "📍 Введите *адрес вашей компании*:\nНапример: ул. Амира Темура 15",
        "reg_done": "🎉 *Регистрация завершена!*",
        "name_label": "👤 Имя",
        "phone_label": "📱 Телефон",
        "company_label": "🏢 Компания",
        "address_label": "📍 Адрес",
        "code_label": "🔑 Ваш код",
        "points_label": "💰 Баллы",
        "daily_info": "🍽 До *15:00* заказ оформляется на сегодня, после *15:00* — на следующий день.\n🚚 Для заказа на сегодня ближайшая доставка — примерно через *60 минут*.",
        "share_phone": "📱 Поделиться номером",
        "phone_saved": "✅ Номер сохранён:",
        "welcome_back": "👋 С возвращением",
        "points": "💰 Баллы",
        "orders": "📦 Заказов",
        "status": "🏅 Статус",
        "orders_closed": "⏰ Приём заказов закрыт!\n\nЗаказы принимаются до *20:00*.\nЗавтра в 10:00 вы получите новое меню 🍽️",
        "no_menu": "😔 Меню на завтра ещё не добавлено.\nОжидайте уведомление в 10:00!",
        "order_accepted": "✅ *Заказ принят! Спасибо!*",
        "delivery_time": "📅 Доставка: завтра с 12:00 до 13:00",
        "my_order": "📋 Ваш заказ на",
        "no_order": "📋 Заказ не оформлен",
        "order_btn": "🍽️ Заказать обед",
        "change_btn": "✏️ Изменить",
        "cancel_btn": "❌ Отменить заказ",
        "confirm_cancel": "❓ Вы уверены что хотите отменить заказ?",
        "yes_cancel": "✅ Да, отменить",
        "back_btn": "◀️ Назад",
        "order_cancelled": "✅ Заказ отменён.",
        "invite_text": "👥 *Пригласи коллегу — получи бонус!*",
        "your_link": "Ваша ссылка:",
        "you_get": "🎁 *Вы получите:* +5 баллов за каждого коллегу",
        "friend_gets": "🎁 *Коллега получит:* +10 баллов при регистрации",
        "menu_title": "🍽️ *Меню на",
        "free_delivery": "🚚 Доставка бесплатно",
        "choose_dish": "Выберите блюдо 👇",
        "reminder": "⏰ *Напоминание!*\n\nВы ещё не заказали обед на завтра.\nОсталось 4 часа — заказы закрываются в *20:00*!\n\n👇 Нажмите *🍽️ Заказать обед*",
        "btn_order": "🍽️ Заказать обед",
        "btn_my_order": "📝 Мой заказ",
        "btn_profile": "🪪 Мой профиль",
        "btn_rating": "🏆 Рейтинг",
        "btn_invite": "👥 Пригласить коллегу",
        "btn_settings": "⚙️ Настройки",
        "btn_admin": "🖥️ Админ панель",
        "btn_auto_on": "🟢 Автозаказ: ВКЛ",
        "btn_auto_off": "🔴 Автозаказ: ВЫКЛ",
        "btn_weekly": "📅 Меню на неделю",
        "loyalty_title": "🎯 *Система лояльности:*",
        "next_reward": "До следующей награды:",
        "all_rewards": "🎉 Все награды получены!",
        "reward_drink": "🥤 *Поздравляем! Вы заработали Напиток!*",
        "reward_dessert": "🍰 *Поздравляем! Вы заработали Десерт!*",
        "reward_lunch": "🍱 *Поздравляем! Вы заработали Бесплатный обед!*",
        "reward_vip": "👑 *Поздравляем! Вы достигли статуса VIP!*",
    },
    "uz_latin": {
        "welcome": (
            "🌿 *Bazilik ga xush kelibsiz!*\n\n"
            "🍱 Biz har kuni ofisингизга\n"
            "yangi uy taomlari yetkazamiz\n\n"
            "✅ Har kuni 3 ta taomdan tanlang\n"
            "✅ Soat 20:00 gacha buyurtma bering\n"
            "✅ Tushlikni 12:00 dan 13:00 gacha oling\n"
            "✅ Ball to'plang va bonuslar oling\n\n"
            "📝 Boshlash uchun *to'liq ismingizni* kiriting:"
        ),
        "select_lang": "🌐 Tilni tanlang:",
        "enter_name": "👋 *To'liq ismingizni* kiriting (Ism Familiya):",
        "enter_phone": "📱 Telefon raqamingizni ulashing:\nQuyidagi tugmani bosing 👇",
        "enter_company": "🏢 *Kompaniya/tashkilot* nomini kiriting:",
        "enter_address": "📍 *Kompaniya manzilingizni* kiriting:\nMasalan: Amir Temur ko'chasi 15",
        "reg_done": "🎉 *Ro'yxatdan o'tish yakunlandi!*",
        "name_label": "👤 Ism",
        "phone_label": "📱 Telefon",
        "company_label": "🏢 Kompaniya",
        "address_label": "📍 Manzil",
        "code_label": "🔑 Sizning kodingiz",
        "points_label": "💰 Ballar",
        "daily_info": "🍽 *15:00 gacha* buyurtma bugunga, *15:00 dan keyin* esa keyingi kunga rasmiylashtiriladi.\n🚚 Bugungi buyurtma uchun eng yaqin yetkazib berish — taxminan *60 daqiqada*.",
        "share_phone": "📱 Raqamni ulashish",
        "phone_saved": "✅ Raqam saqlandi:",
        "welcome_back": "👋 Xush kelibsiz",
        "points": "💰 Ballar",
        "orders": "📦 Buyurtmalar",
        "status": "🏅 Status",
        "orders_closed": "⏰ Buyurtmalar qabul qilinmayapti!\n\nBuyurtmalar *20:00* gacha qabul qilinadi.\nErtaga 10:00 da yangi menyu yuboriladi 🍽️",
        "no_menu": "😔 Ertaga menyu hali qo'shilmagan.\n10:00 da xabarnoma kuting!",
        "order_accepted": "✅ *Buyurtma qabul qilindi! Rahmat!*",
        "delivery_time": "📅 Yetkazib berish: ertaga 12:00 dan 13:00 gacha",
        "my_order": "📋 Buyurtmangiz",
        "no_order": "📋 Buyurtma yo'q",
        "order_btn": "🍽️ Tushlik buyurtma qilish",
        "change_btn": "✏️ O'zgartirish",
        "cancel_btn": "❌ Buyurtmani bekor qilish",
        "confirm_cancel": "❓ Buyurtmani bekor qilmoqchimisiz?",
        "yes_cancel": "✅ Ha, bekor qilish",
        "back_btn": "◀️ Orqaga",
        "order_cancelled": "✅ Buyurtma bekor qilindi.",
        "invite_text": "👥 *Hamkasbingizni taklif qiling — bonus oling!*",
        "your_link": "Sizning havolangiz:",
        "you_get": "🎁 *Siz olasiz:* har bir hamkasb uchun +5 ball",
        "friend_gets": "🎁 *Hamkasb oladi:* ro'yxatdan o'tishda +10 ball",
        "menu_title": "🍽️ *Menyu",
        "free_delivery": "🚚 Yetkazib berish bepul",
        "choose_dish": "Taomni tanlang 👇",
        "reminder": "⏰ *Eslatma!*\n\nSiz hali ertaga tushlik buyurtma qilmadingiz.\n4 soat qoldi — buyurtmalar *20:00* da yopiladi!\n\n👇 *🍽️ Tushlik buyurtma qilish* tugmasini bosing",
        "btn_order": "🍽️ Tushlik buyurtma qilish",
        "btn_my_order": "📝 Mening buyurtmam",
        "btn_profile": "🪪 Mening profilim",
        "btn_rating": "🏆 Reyting",
        "btn_invite": "👥 Hamkasbni taklif qilish",
        "btn_settings": "⚙️ Sozlamalar",
        "btn_admin": "🖥️ Admin panel",
        "btn_auto_on": "🟢 Avtobuyurtma: YOQILGAN",
        "btn_auto_off": "🔴 Avtobuyurtma: O'CHIRILGAN",
        "btn_weekly": "📅 Haftalik menyu",
        "loyalty_title": "🎯 *Sodiqlik tizimi:*",
        "next_reward": "Keyingi mukofotgacha:",
        "all_rewards": "🎉 Barcha mukofotlar olindi!",
        "reward_drink": "🥤 *Tabriklaymiz! Siz Ichimlik yutdingiz!*",
        "reward_dessert": "🍰 *Tabriklaymiz! Siz Desert yutdingiz!*",
        "reward_lunch": "🍱 *Tabriklaymiz! Siz Bepul tushlik yutdingiz!*",
        "reward_vip": "👑 *Tabriklaymiz! Siz VIP statusiga erishdingiz!*",
    },
    "uz_cyrillic": {
        "welcome": (
            "🌿 *Базиликка хуш келибсиз!*\n\n"
            "🍱 Биз ҳар куни офисингизга\n"
            "янги уй таомлари етказамиз\n\n"
            "✅ Ҳар куни 3 та таомдан танланг\n"
            "✅ Соат 20:00 гача буюртма беринг\n"
            "✅ Тушликни 12:00 дан 13:00 гача олинг\n"
            "✅ Балл тўпланг ва бонуслар олинг\n\n"
            "📝 Бошлаш учун *тўлиқ исмингизни* киритинг:"
        ),
        "select_lang": "🌐 Тилни танланг:",
        "enter_name": "👋 *Тўлиқ исмингизни* киритинг (Исм Фамилия):",
        "enter_phone": "📱 Телефон рақамингизни улашинг:\nҚуйидаги тугмани босинг 👇",
        "enter_company": "🏢 *Компания/ташкилот* номини киритинг:",
        "enter_address": "📍 *Компания манзилингизни* киритинг:\nМасалан: Амир Темур кўчаси 15",
        "reg_done": "🎉 *Рўйхатдан ўтиш якунланди!*",
        "name_label": "👤 Исм",
        "phone_label": "📱 Телефон",
        "company_label": "🏢 Компания",
        "address_label": "📍 Манзил",
        "code_label": "🔑 Сизнинг кодингиз",
        "points_label": "💰 Баллар",
        "daily_info": "🍽 *15:00 гача* буюртма бугунга, *15:00 дан кейин* эса кейинги кунга расмийлаштирилади.\n🚚 Бугунги буюртма учун энг яқин етказиб бериш — тахминан *60 дақиқада*.",
        "share_phone": "📱 Рақамни улашиш",
        "phone_saved": "✅ Рақам сақланди:",
        "welcome_back": "👋 Хуш келибсиз",
        "points": "💰 Баллар",
        "orders": "📦 Буюртмалар",
        "status": "🏅 Статус",
        "orders_closed": "⏰ Буюртмалар қабул қилинмаяпти!\n\nБуюртмалар *20:00* гача қабул қилинади.\nЭртага 10:00 да янги менью юборилади 🍽️",
        "no_menu": "😔 Эртага менью ҳали қўшилмаган.\n10:00 да хабарнома кутинг!",
        "order_accepted": "✅ *Буюртма қабул қилинди! Раҳмат!*",
        "delivery_time": "📅 Етказиб бериш: эртага 12:00 дан 13:00 гача",
        "my_order": "📋 Буюртмангиз",
        "no_order": "📋 Буюртма йўқ",
        "order_btn": "🍽️ Тушлик буюртма қилиш",
        "change_btn": "✏️ Ўзгартириш",
        "cancel_btn": "❌ Буюртмани бекор қилиш",
        "confirm_cancel": "❓ Буюртмани бекор қилмоқчимисиз?",
        "yes_cancel": "✅ Ҳа, бекор қилиш",
        "back_btn": "◀️ Орқага",
        "order_cancelled": "✅ Буюртма бекор қилинди.",
        "invite_text": "👥 *Ҳамкасбингизни таклиф қилинг — бонус олинг!*",
        "your_link": "Сизнинг ҳаволангиз:",
        "you_get": "🎁 *Сиз оласиз:* ҳар бир ҳамкасб учун +5 балл",
        "friend_gets": "🎁 *Ҳамкасб олади:* рўйхатдан ўтишда +10 балл",
        "menu_title": "🍽️ *Менью",
        "free_delivery": "🚚 Етказиб бериш бепул",
        "choose_dish": "Таомни танланг 👇",
        "reminder": "⏰ *Эслатма!*\n\nСиз ҳали эртага тушлик буюртма қилмадингиз.\n4 соат қолди — буюртмалар *20:00* да ёпилади!\n\n👇 *🍽️ Тушлик буюртма қилиш* тугмасини босинг",
        "btn_order": "🍽️ Тушлик буюртма қилиш",
        "btn_my_order": "📝 Менинг буюртмам",
        "btn_profile": "🪪 Менинг профилим",
        "btn_rating": "🏆 Рейтинг",
        "btn_invite": "👥 Ҳамкасбни таклиф қилиш",
        "btn_settings": "⚙️ Созламалар",
        "btn_admin": "🖥️ Админ панел",
        "btn_auto_on": "🟢 Автобуюртма: ЁҚИЛГАН",
        "btn_auto_off": "🔴 Автобуюртма: ЎЧИРИЛГАН",
        "btn_weekly": "📅 Ҳафталик менью",
        "loyalty_title": "🎯 *Садоқат тизими:*",
        "next_reward": "Кейинги мукофотгача:",
        "all_rewards": "🎉 Барча мукофотлар олинди!",
        "reward_drink": "🥤 *Табриклаймиз! Сиз Ичимлик ютдингиз!*",
        "reward_dessert": "🍰 *Табриклаймиз! Сиз Десерт ютдингиз!*",
        "reward_lunch": "🍱 *Табриклаймиз! Сиз Бепул тушлик ютдингиз!*",
        "reward_vip": "👑 *Табриклаймиз! Сиз VIP статусига эришдингиз!*",
    }
}


def t(lang: str, key: str) -> str:
    """Получить текст на нужном языке"""
    return TEXTS.get(lang, TEXTS["ru"]).get(key, TEXTS["ru"].get(key, key))
